# Generated by Django 5.2.17 on 2026-08-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Source (nom)'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, help_text='Renseigné automatiquement pour les articles de veille — sert aussi de clé anti-doublon.', max_length=500, null=True, unique=True, verbose_name='Source (URL)'),
        ),
    ]
