# Generated by Django 5.2.17 on 2026-08-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_source_name_article_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Publié immédiatement sans modération. Décoche pour masquer un commentaire a posteriori.', verbose_name='Approuvé'),
        ),
    ]
