# Generated by Django 5.1.6 on 2025-04-18 19:37

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200, null=True, verbose_name='titre')),
                ('contenu', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
    ]
