# Generated by Django 5.1.6 on 2026-06-07 15:22

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='partenaire_img/', verbose_name='Les images Partenaire de logo services')),
                ('contenu', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', tinymce.models.HTMLField(verbose_name='Adresse')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(max_length=100, verbose_name='Téléphone')),
                ('heure_ouverture', tinymce.models.HTMLField()),
            ],
        ),
    ]
