# Generated by Django 5.2.17 on 2026-08-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='fichier',
            field=models.ImageField(blank=True, null=True, upload_to='partenaire_img/', verbose_name='Les images Partenaire de logo services'),
        ),
    ]
