# Generated by Django 5.1.6 on 2025-04-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='titre',
        ),
        migrations.AddField(
            model_name='about_us',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='partenaire_img/', verbose_name='Les images Partenaire de logo services'),
        ),
    ]
