# Generated by Django 5.1.6 on 2025-04-19 15:25

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_about_us_titre_about_us_fichier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=100, verbose_name='Adresse')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(max_length=100, verbose_name='Téléphone')),
                ('heure_ouverture', tinymce.models.HTMLField()),
            ],
        ),
    ]
