# Generated by Django 5.1.6 on 2025-04-19 15:28

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='adresse',
            field=tinymce.models.HTMLField(verbose_name='Adresse'),
        ),
    ]
