# Generated by Django 5.1.6 on 2026-06-07 15:22

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie_Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Categorie de projet')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', tinymce.models.HTMLField(verbose_name='Intitulé de la mission')),
                ('nom_client', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom ou Raison social du Client')),
                ('annee_execution', models.CharField(blank=True, max_length=200, null=True, verbose_name="Année d'execution")),
                ('defis', models.TextField(blank=True, null=True, verbose_name='Défis de la mission')),
                ('solution', models.TextField(blank=True, null=True, verbose_name='Solutions apportées')),
                ('resultat', models.TextField(blank=True, null=True, verbose_name='Resultats attendu')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.categorie_projet', verbose_name='Catégorie de projet')),
            ],
        ),
    ]
