# Generated by Django 5.1.6 on 2025-04-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_projet_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='defis',
            field=models.TextField(blank=True, null=True, verbose_name='Défis de la mission'),
        ),
        migrations.AddField(
            model_name='projet',
            name='resultat',
            field=models.TextField(blank=True, null=True, verbose_name='Resultats attendu'),
        ),
        migrations.AddField(
            model_name='projet',
            name='solution',
            field=models.TextField(blank=True, null=True, verbose_name='Solutions apportées'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='nom_client',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom ou Raison social du Client'),
        ),
    ]
