# Generated by Django 5.1.6 on 2025-04-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_projet_defis_projet_resultat_projet_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie_projet',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
