# Generated by Django 5.1.6 on 2025-04-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_categorie_projet_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie_projet',
            name='slug',
        ),
    ]
