# Generated by Django 5.1.6 on 2025-04-18 19:37

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, verbose_name='Nom du Services')),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
    ]
