# Generated by Django 5.1.6 on 2025-04-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0002_services_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newletter_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Nom du Services')),
            ],
        ),
    ]
